apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: oms-schema-password
  namespace: {{ .Release.Namespace }}
  labels:
      application: {{ .Chart.Name }}
data:
  # BRM root password
  brm_root_password: {{ .Values.ocbrm.brm_root_pass }}

  #DB Schema Password
  oms_schema_password: {{ .Values.ocbrm.db.schemapass }}

  pipeline_schema_password: {{ .Values.ocbrm.db.pipelineschemapass }}

  #BRM Server Wallet Password 
  client_wallet_password: {{ .Values.ocbrm.wallet.client }}

  #BRM Server Wallet Password 
  server_wallet_password: {{ .Values.ocbrm.wallet.server }}

  #BRM Root Wallet Password 
  root_wallet_password: {{ .Values.ocbrm.wallet.root }}

  #DO NOT CHANGE
  old_client: QzFnMmIzdTQ=
  #DO NOT CHANGE
  old_root: QzFnMmIzdTQ=

